# Generated by Django 5.1.6 on 2025-03-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="prescribed_amount",
            field=models.IntegerField(default=1),
        ),
    ]
