# Generated by Django 5.1.6 on 2025-03-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0002_prescription_prescribed_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="expiration_date",
            field=models.DateField(
                blank=True, help_text="Format: YYYY-MM-DD", null=True
            ),
        ),
    ]
